### PR TITLE
fix(skhd): deprecated plist to service with logging

### PR DESCRIPTION
**Pull request by jorpilo**
Adding another PR to see if we can get this going.

This includes the skhd changes from #27 without the logging parameter

If you want to test it you can tap the master branch of my work which should include the updated formulae

### CODE REVIEW

**Comment by jorpilo** [comment]
@mvllow can you verify if there is any further comment?

**Comment by mvllow** [comment]
Both this and #31 look great :)

**Comment by jorpilo** [comment]
Who needs to merge this? @koekeishiya could you review and merge?

**Comment by koekeishiya** [comment]
Same issue as with #31, waiting for Brew to fix their API.

**Comment by koekeishiya** [comment]
Will probably add launchd integration directly into skhd and rework how logging works; see https://github.com/koekeishiya/yabai/issues/1619#issuecomment-1507686308 for description of how this works in yabai.

**Comment by koekeishiya** [comment]
Replaced brew services.

**Pull request closed without merging**
